# Generated by Django 3.1.7 on 2021-03-07 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContFirmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('firmware', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ino'])])),
                ('comment', models.TextField(blank=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
